### PR TITLE
add docker layer caching and `nb_conda_kernels`

### LINKED ISSUE #10: use `nb_conda_kernels` instead of installing each kernel manually
`nb_conda_kernels` has more features, for ex: it would allow us to run tools installed in those environments using `%%bash` from within the notebooks

we just need to install it within whatever environment has `jupyterlab` installed. Our Dockerfile seems to use [this one](https://github.com/jupyter/docker-stacks/blob/5a67b4e868cd4b243ac83b1a7d39b2b080e4eff6/base-notebook/Dockerfile#L142) as its primary base image, which seems to install `jupyterlab` in the _base_ environment. So all we need to do is add this to the Dockerfile:
```
mamba install -y -c conda-forge nb_conda_kernels
```

### PR DESCRIPTION
**Pull request by aryarm**
This PR makes two changes:
1. It adds [docker layer caching](https://docs.docker.com/build/cache/backends/gha/) to our Github action via [these changes](https://github.com/biom262/cmm262-notebook/compare/50e57aea...c649a379)
    This allows us to cache portions of our build process, so that re-builds happen only for the portions of our Dockerfile that need to be rerun, potentially saving us substantial amounts of time.
    For example, let's say that we make a commit in which the only change is to one of our conda environment files. And let's say that the environment file in question gets `COPY`-ed into the container on line 10 of the Dockerfile.
    Docker layer caching means that when the container image gets rebuilt for this commit, Docker will automatically restart the build process on line 10 instead of starting from the beginning of the Dockerfile.
2. It adds `nb_conda_kernels` in our Dockerfile and resolves #10

### CODE REVIEW

**Comment by aryarm** [comment]
Wesley, I'm marking you as a reviewer in case you have any comments. Besides a quick check on our work, we'd be curious to hear if you think any of these changes might have unintended side effects or if there are consequences we might not have considered. But also feel free to ignore this PR, especially if you're out for a (well deserved) holiday break now!

**Comment by aryarm** [comment]
Not sure why the build failed. The logs seem to indicate that it's some sort of permission issue. I'm guessing it's something to due with the fact that this PR originates from a fork.

**Comment by wesuuu** [comment]
@aryarm  Your changes look good and I looked into this issue. I'm not sure if it's possible for a forked branch from another organization (e.g. `biom262`) is able to push to this `ghcr.io` repo (see https://github.com/docker/build-push-action/issues/463#issuecomment-926229761).

In any case, once you merge the pull request, the action should clear if the docker build is successful.

**Comment by aryarm** [comment]
ok, thanks for the quick response!

merging now

**Pull request merged**
